### ISSUE TITLE
USE PULL REQUESTS AND CODE REVIEW!!!!!!!

### ISSUE THREAD

**Issue by ibara** [hbh7/RINFO#5]
There are 142 commits to the master branch, 3 pull requests total, and no branches.

Use pull requests, demand code review. Don't just commit stuff (and never commit directly to master--you're going to cause yourself and your group members serious headaches at the worst possible time).

**Comment by hbh7** [comment]
It's been determined to be worth the risk, as we have bigger issues at hand and I can fix any issues as I already had to for Hexed. Too many different time constraints and interworking and other issues for pull requests and branches to be anything but a hindrance at the moment. 

Normally though yes branches and pull requests would be great.

**Comment by ibara** [comment]
Then you all have something to improve upon next semester, and I will keep close tabs on that.

**Comment by hbh7** [comment]
Oh absolutely, but deadlines approach now

**Comment by xianlany** [comment]
I've been having a lot of issues with both the Github desktop client as well as Gitkraken now. For some reason my computer just occasionally bugs my repo so that I am unable to commit, which results in me having to delete the entire repo and clone it fresh.

**Comment by xianlany** [comment]
We've also run into many merge conflicts and other weird issues with version control where the repo is updated but a machine won't recognize the changes

**Comment by ibara** [comment]
Merge conflicts is almost always a result of not using branches.
I've not used Gitkraken before, so unfortunately I can't be too much help there without seeing what is going on. In the worst case scenario, you can always fall back to using the command-line git program (it's what I use!).

**Comment by tremag** [comment]
It's true that at the beginning we did have quite a few merge conflicts, but after improving on communication and more clearly defining what each group member is working on at any one time, merge conflicts have been rare recently.
Currently, I think we do a pretty good job of communicating when we have made any change that might affect what anyone else is working on, either on the slack or on the group sms we created.
I can't speak for my group members, but normally, the first thing I would have done when learning git would've been to start in the terminal and learn the basic commands and syntax, then move to the GUI once I had a solid grasp on the underlying technology.
However, due to time constraints, I was forced to pretty much skip that step and jump straight into the GUI, learning only what was necessary to get the job done. Because of that, falling back to the command line is technically an option, but it would likely require time that I'm not sure we can spare at the moment.
Anyway, given the current situation and timeline, I agree with Hunter's statement. Out of consideration for Lanya's finicky machine and because of time constraints, we have tried to simplify our workflow as much as possible while also minimizing the risk of things like merge conflicts and accidentally breaking something on the site. Unfortunately, that means mostly committing to the master branch and accepting the risks that come with that.
Again, I can't speak for my teammates, but in an attempt to make up for that, I do not push code to the master branch without thoroughly testing it first. Of course I will not be able to catch every error or bug that my code might introduce, but in this situation, I do believe that it is the best combination of efficiency and simplicity.
Just my 2¢ :)
